#!/usr/bin/env bash
# a bash script to change some ip addresses in the hostfile

# first make a copy of hosts
cp /etc/hosts ~/hosts.new
# using sed and regexp we serach and replace the required IP
sed 's/^127.0.0.1$/127.0.0.2' ~/hosts.new
# lets append another entry
echo "8.8.8.8	facebook.com" >> ~/hosts.new
# replace the official hosts file with our copy
cat ~/hosts.new > /etc/hosts
